# Config version
version: 1.0

# Experiment description, used in the output dir name
desc: multilabel-global_lepi

# Training hyperparameters
train:
    parquet_path: /work/datasets/global_lepi/0032836-250426092105405_processing_metadata_postprocessed_quality_filtered.parquet
    img_dir: /work/datasets/global_lepi/images
    out_dir: "/work/GuillaumeMougeot#5298/lepinet/data/models"
    fold: '1'
    img_per_spc: 50
    model_name: multilabel-global_lepi-effnetv2m
    nb_epochs: 10
    batch_size: 64
    aug_img_size: 460
    img_size: 256
    model_arch_name: efficientnet_v2_m
    hierarchy_path: null

test: # flemming test
    img_dir: /work/datasets/flemming_helsing/resized/valid/referenced
    model_path: /work/GuillaumeMougeot#5298/lepinet/data/models/20251105-112242-multilabel-global_lepi/models/multilabel-global_lepi-effnetv2m_5.pth
    out_dir: /work/GuillaumeMougeot#5298/lepinet/data/preds