# Config version
version: 1.0

# Experiment description, used in the output dir name
desc: dev_mini

# Training hyperparameters
train:
    parquet_path: /home/george/codes/lepinet/data/mini/0013397-241007104925546_processing_metadata_postprocessed.parquet
    img_dir: /home/george/codes/lepinet/data/mini/images
    out_dir: /home/george/codes/lepinet/data/mini/models
    fold: '1'
    img_per_spc: 5
    model_name: mini_1.0
    nb_epochs: 20
    batch_size: 64
    aug_img_size: 460
    img_size: 256
    model_arch_name: resnet18
    hierarchy_path: null
